// Code generated by mkegg; DO NOT EDIT
package eggs

import "bytes"

var private_TXT_HelloWorld = [...]byte{
	72,101,108,108,111,44,32,119,111,114,108,100,33,10,
}

func TXT_HelloWorld() *bytes.Reader {
	return bytes.NewReader(private_TXT_HelloWorld[:])
}
